### ISSUE TITLE
osx - UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte

### ISSUE THREAD

**Issue by johndpope** [llSourcell/tensorflow_chatbot#1]
steps - I used the cpu only option

# Mac OS X, CPU only, Python 3.4 or 3.5:
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0rc0-py3-none-any.whl

# Mac OS X, GPU enabled, Python 3.4 or 3.5:
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-0.12.0rc0-py3-none-any.whl
Install TensorFlow:

# Python 3
$ sudo pip3 install --upgrade $TF_BINARY_URL

 python3 execute.py

>> Mode : train

Preparing data in working_dir/
Tokenizing data in data/train.enc
Traceback (most recent call last):
  File "execute.py", line 300, in <module>
    train()
  File "execute.py", line 114, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "/Users/johndpope/Documents/gitWorkspace/tensorflow_chatbot/data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "/Users/johndpope/Documents/gitWorkspace/tensorflow_chatbot/data_utils.py", line 112, in data_to_token_ids
    vocab, _ = initialize_vocabulary(vocabulary_path)
  File "/Users/johndpope/Documents/gitWorkspace/tensorflow_chatbot/data_utils.py", line 87, in initialize_vocabulary
    rev_vocab.extend(f.readlines())
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 131, in readlines
    s = self.readline()
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 124, in readline
    return compat.as_str_any(self._read_buf.ReadLineAsString())
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte

**Comment by johndpope** [comment]
<img width="517" alt="screen shot 2016-12-02 at 22 04 55" src="https://cloud.githubusercontent.com/assets/289994/20856377/3b72283a-b8db-11e6-8dd5-4ef17801d9d4.png">
tensorflow is correctly working.

**Comment by johndpope** [comment]
it's saying the files are in utf-8 format
<img width="666" alt="screen shot 2016-12-02 at 22 21 12" src="https://cloud.githubusercontent.com/assets/289994/20856471/7b39abd0-b8dd-11e6-8626-32835e0bc2aa.png">

**Comment by johndpope** [comment]
https://github.com/llSourcell/tensorflow_chatbot/pull/2
