### ISSUE TITLE
encoder data /train.enc no data found

### ISSUE THREAD

**Issue by saran-gangster** [llSourcell/tensorflow_chatbot#102]
Warning (from warnings module):
  File "H:\python\tensorflow - chatbots\tensorflow_chatbot-master\execute.py", line 50
    parser = SafeConfigParser()
DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.

>> Mode : train

Preparing data in working_dir/
Tokenizing data in data/train.enc
Traceback (most recent call last):
  File "H:\python\tensorflow - chatbots\tensorflow_chatbot-master\execute.py", line 319, in <module>
    train()
  File "H:\python\tensorflow - chatbots\tensorflow_chatbot-master\execute.py", line 127, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "H:\python\tensorflow - chatbots\tensorflow_chatbot-master\data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "H:\python\tensorflow - chatbots\tensorflow_chatbot-master\data_utils.py", line 116, in data_to_token_ids
    for line in data_file:
  File "F:\python 3.8\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 211, in __next__
    return self.next()
  File "F:\python 3.8\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 205, in next
    retval = self.readline()
  File "F:\python 3.8\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 169, in readline
    self._preread_check()
  File "F:\python 3.8\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 78, in _preread_check
    self._read_buf = _pywrap_file_io.BufferedInputStream(
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: data/train.enc : The system cannot find the path specified.

; No such process

**Comment by saran-gangster** [comment]
please help with this

**Comment by Rowan404** [comment]
I have the same problem. How did you solve it?
