### ISSUE TITLE
No module named models.rnn.translate

### ISSUE THREAD

**Issue by AnupKumarGupta** [llSourcell/tensorflow_chatbot#26]
**Traceback (most recent call last):**
  File "execute.py", line 31, in <module>
   ` import seq2seq_model`
  File "/home/textsum/Documents/TensorFlow/tensorflow_chatbot/seq2seq_model.py", line 28, in <module>
   ` from tensorflow.models.rnn.translate import data_utils`
**ImportError**: No module named models.rnn.translate

**Comment by Graystripe17** [comment]
Use TensorFlow 0.12.0 instead of TensorFlow 1.0.0

**Comment by RathanakSreang** [comment]
@Graystripe17 
do you have other solution beside using old version?

**Comment by Graystripe17** [comment]
@RathanakSreang if you try to go in and change the import a dozen of other changes spring up. If you want to use the latest version, wait for TF1.1 because I messaged some of the workers at TF and they promised to move the modules back

**Comment by chrismpalmer** [comment]
Friends! I am running 0.12.0 and getting this same problem. I appear to have the right config. I am using the tensorflow docker 0.12.0 so everything should be intact perhaps its built on a release candidate.

**Comment by Graystripe17** [comment]
@chrismpalmer You using python 2.7?

**Comment by chrismpalmer** [comment]
@Graystripe17 

root@5d8738fee03e:/notebooks# python --version
Python 2.7.6

**Comment by Graystripe17** [comment]
@chrismpalmer I'm sorry I don't really have a good solution for you. If it's the exact same installation, I don't think it should be giving you this particular error. I used virtualenv and am not familiar with docker. Maybe give that a shot?

**Comment by chrismpalmer** [comment]
@Graystripe17 thanks a lot. I do notice there is a local data_utils and seq2seq_model imports a tensor flow one. I wonder if this is intended.

**Comment by chrismpalmer** [comment]
@Graystripe17 That was the problem. I am training now. Doesn't look like it uses the gpu for training at all.

**Comment by ImGokulM** [comment]
I'm also getting the same error,

Traceback (most recent call last):
  File "execute.py", line 31, in <module>
    import seq2seq_model
  File "D:\Development\ML\TensorFlow\tensorflow_chatbot-master\seq2seq_model.py", line 28, in <module>
    from tensorflow.models.rnn.translate import data_utils
ImportError: No module named 'tensorflow.models'


Please help if anyone fixed this.

**Comment by ImGokulM** [comment]
Worked!
As @Graystripe17  said, in seq2seq_model.py you need to replace the line #28 
'from tensorflow.models.rnn.translate import data_utils' with 'import data_utils'.
Thanks  @Graystripe17!

**Comment by Graystripe17** [comment]
@ImGokulM @chrismpalmer No problem! @AnupKumarGupta If this solved your issue, you can close this.

**Comment by athuldevin** [comment]
i have the same issue and i applied the fix it works ,but it throws another error for both train and test

>> Mode : test

Traceback (most recent call last):
  File "C:\Users\win-7\Downloads\Compressed\tensorflow_chatbot-master\execute.py", line 322, in <module>
    decode()
  File "C:\Users\win-7\Downloads\Compressed\tensorflow_chatbot-master\execute.py", line 211, in decode
    model = create_model(sess, True)
  File "C:\Users\win-7\Downloads\Compressed\tensorflow_chatbot-master\execute.py", line 104, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "C:\Users\win-7\Downloads\Compressed\tensorflow_chatbot-master\seq2seq_model.py", line 98, in __init__
    single_cell = tf.nn.rnn_cell.GRUCell(size)
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

**Comment by elihanover** [comment]
After I do that I get 

Traceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 127, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "/Users/eli/Downloads/tensorflow_chatbot-master/data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "/Users/eli/Downloads/tensorflow_chatbot-master/data_utils.py", line 116, in data_to_token_ids
    for line in data_file:
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 164, in next
    retval = self.readline()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 133, in readline
    self._preread_check()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 75, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: data/train.enc

**Comment by elihanover** [comment]
I'm getting the same thing as @athuldevin after fixing line 28.  Any ideas on what this could possibly be?

**Comment by jmoney4769** [comment]
See https://github.com/llSourcell/tensorflow_chatbot/issues/46 on how to get it working with 1.2.  Also the Tensorflow release notes talk about where packages get moved to.

**Comment by LockGit** [comment]
I'm getting the same thing as @AnupKumarGupta .
use tensorflow  docker container
Python 2.7.12

**Comment by sujeet1747** [comment]
You can uninstall using the following shell script___ 
sudo pip uninstall tensorflow
and roll back by ____
sudo pip install tensorflow==0.12

**Comment by sujeet1747** [comment]
The conversation were gibberish. One I'd like to mention

>Where are you ?
orgy orgy orgy orgy orgy orgy orgy orgy orgy orgy orgy orgy 

Where is the error, folks ?

**Comment by LockGit** [comment]
thx

**Comment by ghost** [comment]
I'm getting the same problem....
