### ISSUE TITLE
Error executing python execute.py after installing the dependencies (i had installed tensorflow in virtualenv)

### ISSUE THREAD

**Issue by rahulpahuja** [llSourcell/tensorflow_chatbot#47]
Traceback (most recent call last):
  File "execute.py", line 31, in <module>
    import seq2seq_model
  File "/Users/rahul/Desktop/AI and ML/tensorflow_chatbot-master/seq2seq_model.py", line 28, in <module>
    from tensorflow.models.rnn.translate import data_utils
ImportError: No module named models.rnn.translate

**Comment by bman46** [comment]
what version of Tensorflow do you have?

**Comment by bandarikanth** [comment]
To Resolve Use < 1.0 tensorflow Version
and change command tf.nn.seq2seq to tf.contrib.legacy_seq2seq model
