### ISSUE TITLE
Error while running execute.py

### ISSUE THREAD

**Issue by SAGARSURI** [llSourcell/tensorflow_chatbot#5]
getting this error while executing "python3 execute.py"
Help please

`Traceback (most recent call last):
  File "execute.py", line 303, in <module>
    decode()
  File "execute.py", line 199, in decode
    enc_vocab, _ = data_utils.initialize_vocabulary(enc_vocab_path)
  File "/Users/sagarsuri/Downloads/tensorflow_chatbot-master/data_utils.py", line 87, in initialize_vocabulary
    rev_vocab.extend(f.readlines())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 131, in readlines
    s = self.readline()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/lib/io/file_io.py", line 124, in readline
    return compat.as_str_any(self._read_buf.ReadLineAsString())
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte`

**Comment by johndpope** [comment]
Try the pull request

**Comment by salman-bhai** [comment]
Did it work after the Pull Request?

**Comment by 1228337123** [comment]
you should change the data that is under the work_dir folder to 'UTF-8' format. Then maybe you can run. It's work for me . ^_^

**Comment by HazeHub** [comment]
This code is intended to work on Python 3. 
If you absolutely need to run it with Python 3, hold on I'll update my fork of this project with some code that works on Python 3.
