### ISSUE TITLE
'module' object has no attribute 'seq2seq'

### ISSUE THREAD

**Issue by bugsbunny1996** [llSourcell/tensorflow_chatbot#53]
I run the execute.py and receive this error. 
`>> Mode : train

Preparing data in working_dir/
2017-07-30 20:40:34.971282: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-30 20:40:34.971452: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-30 20:40:34.971593: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-30 20:40:34.971732: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-30 20:40:34.971872: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Creating 3 layers of 256 units.
Traceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 137, in train
    model = create_model(sess, False)
  File "execute.py", line 104, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "/home/bugsbunny/tensorflow_chatbot/seq2seq_model.py", line 146, in __init__
    self.outputs, self.losses = tf.nn.seq2seq.model_with_buckets(
AttributeError: 'module' object has no attribute 'seq2seq'`

My tensorflow version is 1.2 and so is my tensorflow-gpu

**Comment by ashwanijha04** [comment]
I am facing the same issue. What might be the solution to this?

**Comment by bugsbunny1996** [comment]
I searched up google and found out that the seq2seq model was changed from the tf.nn model now in the latest update. You can install and older version <1.0 of tensorflow and tensorflow-gpu from the archives.

**Comment by ghost** [comment]
Do you know the changes that have to be done? 
There is no older version of TF on pip available...

**Comment by siddarthsreeni-zz** [comment]
The older versions to TF are available here.
https://www.tensorflow.org/versions/

**Comment by wanesta** [comment]
I got this issue of  TensorFlow version 1.3.

**Comment by clintjcampbell** [comment]
I know that in the RNN Seqence to Sequence  Translate example they provided some changes recently to fix for 1.3.  I assume the import issues are probably similar to what they have done, as it is mostly the same code base.  Trying to get this to work as well for 1.3.

**Comment by bandarikanth** [comment]
To Resolve Use < 1.0 tensorflow Version 
and change command tf.nn.seq2seq    to      tf.contrib.legacy_seq2seq model

**Comment by blindfish** [comment]
Running into this error as well. Is there an easy way to update the code vs. downgrade to a much earlier version of Tensorflow?

**Comment by siddarthsreeni-zz** [comment]
I had been able to fix the errors and run the code properly, Like I commented previously, downgrading to tensorflow < 1.0 will fix the error. I dont know about @bandarikanth  who mentioned about updating to contrib.legacy. Although it seems to be working fine for "him/her"

**Comment by PR-Iyyer** [comment]
I am using tf version 0.12.1 . it is also giving same error? Can someone please help me to fix it?

**Comment by bandarikanth** [comment]
Use tensor flow 0.12.0
And update some code
Tensor flow.contrib.legacy

See this about tensorflow.org

**Comment by neonb88** [comment]
These are the 3 steps I had to do to get it working.  I hope this helps.  I am running Ubuntu 16.04 running

1. Download prev version of tf:  https://stackoverflow.com/questions/40416056/how-to-download-previous-version-of-tensorflow
2.  Solution to another issue that popped up: https://github.com/tensorflow/models/issues/1736 (Stephen Lee's comment)
3. https://stackoverflow.com/questions/44855603/typeerror-cant-pickle-thread-lock-objects-in-seq2seq
