### ISSUE TITLE
I meet a problem when I change the mode = test. Can anybody help me please 

### ISSUE THREAD

**Issue by xiaoyaomimi** [llSourcell/tensorflow_chatbot#60]
Here is the detial error message : 
     File "execute.py", line 218, in decode
    enc_vocab, _ = data_utils.initialize_vocabulary(enc_vocab_path)
  File "E:\tensorflow-seq2seq-chatbot-master\tensorflow-seq2seq-chatbot-master\data_utils.py", line 89, in initialize_vocabulary
    rev_vocab.extend(f.readlines())
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 131, in readlines
    s = self.readline()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 124, in readline
    return compat.as_str_any(self._read_buf.ReadLineAsString())
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\util\compat.py", line 106, in as_str_any
    return as_str(value)
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\util\compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte

**Comment by wanesta** [comment]
有中文注释没有？

**Comment by xiaoyaomimi** [comment]
没有中文注释啊，都是英文

**Comment by blindfish** [comment]
Also running into this issue. Anyone find a solution?

```
Reading model parameters from working_dir/seq2seq.ckpt-11100
Traceback (most recent call last):
  File "execute.py", line 322, in <module>
    decode()
  File "execute.py", line 218, in decode
    enc_vocab, _ = data_utils.initialize_vocabulary(enc_vocab_path)
  File "/home/user/Documents/GitHub/tensorflow_chatbot/data_utils.py", line 87, in initialize_vocabulary
    rev_vocab.extend(f.readlines())
  File "/home/user/anaconda3/envs/python27/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 131, in readlines
    s = self.readline()
  File "/home/user/anaconda3/envs/python27/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 124, in readline
    return compat.as_str_any(self._read_buf.ReadLineAsString())
  File "/home/user/anaconda3/envs/python27/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 106, in as_str_any
    return as_str(value)
  File "/home/user/anaconda3/envs/python27/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1: invalid start byte
```
