### ISSUE TITLE
While training the seq2seq the program gets killed i am using CPU only tensorflow

### ISSUE THREAD

**Issue by KhajaMoinuddin** [llSourcell/tensorflow_chatbot#63]
root@ubuntu:~/tensorflow/chatbot/tensorflow_chatbot-master# python execute.py 

>> Mode : train

Preparing data in working_dir/
Creating 3 layers of 256 units.
before creating model
inside_create_model
Killed

**Comment by ghost** [comment]
i am getting similar....in Train
reating 3 layers of 256 units.
Traceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 137, in train
    model = create_model(sess, False)
  File "execute.py", line 104, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "/Users/charlesyau/Desktop/tensorflow_chatbot-master/seq2seq_model.py", line 154, in __init__
    self.outputs, self.losses = tf.nn.seq2seq.model_with_buckets(
AttributeError: 'module' object has no attribute 'seq2seq'

**Comment by gamegoofs2** [comment]
Any solution to this yet?

**Comment by irisyjohnson** [comment]
Getting the same while training on gcloud with cpu
