### ISSUE TITLE
TypeError: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by Klas96** [llSourcell/tensorflow_chatbot#69]
Seam to be giving me an error when making the vocab20000 file.

>> Mode : train

Preparing data in working_dir/
Creating vocabulary working_dir/vocab20000.enc from data/train.enc
  processing line 100000
>> Full Vocabulary Size : 45504
>>>> Vocab Truncated to: 20000
Traceback (most recent call last):
  File "execute.py", line 352, in <module>
    train()
  File "execute.py", line 138, in train
    gConfig['dec_vocab_size'])
  File "/home/klas/Documents/Python/Untitled Folder/tensorflow_chatbot-master/data_utils.py", line 135, in prepare_custom_data
    create_vocabulary(enc_vocab_path, train_enc, enc_vocabulary_size, tokenizer)
  File "/home/klas/Documents/Python/Untitled Folder/tensorflow_chatbot-master/data_utils.py", line 85, in create_vocabulary
    vocab_file.write(w + '\n')
TypeError: write() argument 1 must be unicode, not str

**Comment by dineshobjects** [comment]
I am facing same problem. Please advise.

**Comment by tusharjayanti** [comment]
I am also facing the same error. Please help.

**Comment by cprovatas** [comment]
Same error please help
