### ISSUE TITLE
Python newb stuck launching execute

### ISSUE THREAD

**Issue by ianakelly** [llSourcell/tensorflow_chatbot#7]
Love the videos and the live coding is great too ;)

But I am struggling to get the project running as is before I start to make changes.

When I run $python execute.py I get the following
python execute.py

>> Mode : train

Preparing data in working_dir/
Tokenizing data in data/train.enc
Traceback (most recent call last):
  File "execute.py", line 309, in <module>
    train()
  File "execute.py", line 123, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "/Users/kelia01/Downloads/tensorflow_chatbot-master/data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "/Users/kelia01/Downloads/tensorflow_chatbot-master/data_utils.py", line 116, in data_to_token_ids
    for line in data_file:
  File "/Library/Python/2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 156, in next
    retval = self.readline()
  File "/Library/Python/2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 123, in readline
    self._preread_check()
  File "/Library/Python/2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 73, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Library/Python/2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: data/train.enc

I walked the execution of the code manually but cannot figure out how it's not getting the data/train.enc

Thanks all!

**Comment by HazeHub** [comment]
Did you even read other issues threads ? I'll guess you're just not getting what's wrong with the code :

> tensorflow.python.framework.errors_impl.NotFoundError: data/train.enc

The last line tells you there is not data/train.enc file ... From here you can just look at the other issues like this one : https://github.com/llSourcell/tensorflow_chatbot/issues/3 Everything is explained in the discussion ;-)

**Comment by ianakelly** [comment]
Thanks @HazeHub will look at that - I have tried to download that data too but no joy yet...
