### ISSUE TITLE
Get this error how to solve it.

### ISSUE THREAD

**Issue by thedevankit** [llSourcell/tensorflow_chatbot#70]
C:\Users\ANKIT\Downloads\TENSORFLOW MODELS\tensor chat\tensorflow_chatbot000-master\tensorflow_chatbot-master\data>python execute.py

>> Mode : train

Preparing data in working_dir/
Tokenizing data in data/train.enc
Traceback (most recent call last):
  File "execute.py", line 352, in <module>
    train()
  File "execute.py", line 138, in train
    gConfig['dec_vocab_size'])
  File "C:\Users\ANKIT\Downloads\TENSORFLOW MODELS\tensor chat\tensorflow_chatbot000-master\tensorflow_chatbot-master\data\data_utils.py", line 141, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "C:\Users\ANKIT\Downloads\TENSORFLOW MODELS\tensor chat\tensorflow_chatbot000-master\tensorflow_chatbot-master\data\data_utils.py", line 126, in data_to_token_ids
    normalize_digits)
  File "C:\Users\ANKIT\Downloads\TENSORFLOW MODELS\tensor chat\tensorflow_chatbot000-master\tensorflow_chatbot-master\data\data_utils.py", line 108, in sentence_to_token_ids
    words = tokenizer(sentence)
  File "C:\Users\ANKIT\Downloads\TENSORFLOW MODELS\tensor chat\tensorflow_chatbot000-master\tensorflow_chatbot-master\data\data_utils.py", line 51, in basic_tokenizer
    words = re.split(_WORD_SPLIT, space_separated_fragment)
  File "C:\Users\ANKIT\AppData\Local\Programs\Python\Python35\lib\re.py", line 203, in split
    return _compile(pattern, flags).split(string, maxsplit)
TypeError: cannot use a string pattern on a bytes-like object

C:\Users\ANKIT\Downloads\TENSORFLOW MODELS\tensor chat\tensorflow_chatbot000-master\tensorflow_chatbot-master\data>train

**Comment by andyhappy1** [comment]
It looks like maybe you are using python3?  You should try using python 2.7.

**Comment by dianad96** [comment]
Has anyone made this work with python3? I am having the same issue

**Comment by thedevankit** [comment]
Has anyone solve this error.

**Comment by vincentandreas** [comment]
i think you must change the encoding file from utf-8 to iso-8859-1 (test.enc, train.enc, test.dec, train.dec)

import codecs
BLOCKSIZE = 1048576 # or some other, desired size in bytes
sourceFileName = '/content/gdrive/My Drive/Colab Notebooks/tensorflow-siraj-chatbot/tensorflow_chatbot-master/data/train.dec'
targetFileName = '/content/gdrive/My Drive/Colab Notebooks/tensorflow-siraj-chatbot/tensorflow_chatbot-master/data/train.dec'
with codecs.open(sourceFileName, "r", "utf-8") as sourceFile:
    with codecs.open(targetFileName, "w", "iso-8859-1") as targetFile:
        while True:
            contents = sourceFile.read(BLOCKSIZE)
            if not contents:
                break
            targetFile.write(contents)
