### ISSUE TITLE
So this happened when I tried to run execute.py

### ISSUE THREAD

**Issue by kaiwenliu** [llSourcell/tensorflow_chatbot#71]
Traceback (most recent call last):
  File "C:\Users\jun\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 47, in preload_check
    ctypes.WinDLL(build_info.msvcp_dll_name)
  File "C:\Users\jun\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jun\Desktop\tensorflow_chatbot-master\execute.py", line 28, in <module>
    import tensorflow as tf
  File "C:\Users\jun\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\jun\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\jun\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Users\jun\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\self_check.py", line 55, in preload_check
    % build_info.msvcp_dll_name)
ImportError: Could not find 'msvcp140.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. You may install this DLL by downloading Visual C++ 2015 Redistributable Update 3 from this URL: https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by w9ahmed** [comment]
I'm getting an error as well, but not the same (I'm using Ubuntu)

```
Preparing data in working_dir/
Tokenizing data in data/train.enc
Traceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 127, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "/home/w9ahmed/Documents/Projects/tensorflow_chatbot/data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "/home/w9ahmed/Documents/Projects/tensorflow_chatbot/data_utils.py", line 116, in data_to_token_ids
    for line in data_file:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 207, in next
    retval = self.readline()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 176, in readline
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: data/train.enc
```

**Comment by tirdtoon** [comment]
https://github.com/llSourcell/tensorflow_chatbot/issues/55

**Comment by alisonhc** [comment]
I'm getting the error @w9ahmed getting, and I'm using Windows.

**Comment by tapasrm** [comment]
@kaiwenliu did you try running the script after updating Visual C++, seems that `msvcp140.dll` is required by Tensorflow for the proper execution
