### ISSUE TITLE
Error when running execute.py - missing directory data? 

### ISSUE THREAD

**Issue by w9ahmed** [llSourcell/tensorflow_chatbot#72]
Can't find files: 
```
train_enc = data/train.enc
train_dec = data/train.dec
test_enc = data/test.enc
test_dec = data/test.enc
```

When I execute, I get this error 
```
Preparing data in working_dir/
Tokenizing data in data/train.enc
Traceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 127, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "/home/w9ahmed/Documents/Projects/tensorflow_chatbot/data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "/home/w9ahmed/Documents/Projects/tensorflow_chatbot/data_utils.py", line 116, in data_to_token_ids
    for line in data_file:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 207, in next
    retval = self.readline()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 176, in readline
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: data/train.enc
```

**Comment by w9ahmed** [comment]
nvm, I saw someone had the similar issue
https://github.com/llSourcell/tensorflow_chatbot/issues/55#issuecomment-338099223

Closing as its a duplicate.
