### ISSUE TITLE
Issue with execute.py

### ISSUE THREAD

**Issue by haylinmoore** [llSourcell/tensorflow_chatbot#76]
I try to run execute.py and get 

>> Mode : train

Preparing data in working_dir/
Tokenizing data in data/train.enc
Traceback (most recent call last):
  File "execute.py", line 319, in <module>
    train()
  File "execute.py", line 127, in train
    enc_train, dec_train, enc_dev, dec_dev, _, _ = data_utils.prepare_custom_data(gConfig['working_directory'],gConfig['train_enc'],gConfig['train_dec'],gConfig['test_enc'],gConfig['test_dec'],gConfig['enc_vocab_size'],gConfig['dec_vocab_size'])
  File "/var/www/tensorflow_chatbot/data_utils.py", line 137, in prepare_custom_data
    data_to_token_ids(train_enc, enc_train_ids_path, enc_vocab_path, tokenizer)
  File "/var/www/tensorflow_chatbot/data_utils.py", line 116, in data_to_token_ids
    for line in data_file:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 208, in next
    retval = self.readline()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 177, in readline
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 79, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: data/train.enc; No such file or directory

Note all I did was clone the repo, and I am using python 2.7

**Comment by 3dozens** [comment]
You need to prepare train/test data by yourself. 
Check this https://github.com/llSourcell/tensorflow_chatbot/issues/55#issuecomment-320599287
and this https://github.com/llSourcell/tensorflow_chatbot/issues/9#issuecomment-265867981
