### ISSUE TITLE
i don't know what's mean Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2

### ISSUE THREAD

**Issue by ckc5800** [llSourcell/tensorflow_chatbot#79]
I am a student studying tensor flow.
Can I get help?
i used window, powershell

-master> python .\execute.py

>> Mode : test

2018-01-16 12:11:02.578204: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
Traceback (most recent call last):
  File ".\execute.py", line 322, in <module>
    decode()
  File ".\execute.py", line 211, in decode
    model = create_model(sess, True)
  File ".\execute.py", line 104, in create_model
    model = seq2seq_model.Seq2SeqModel( gConfig['enc_vocab_size'], gConfig['dec_vocab_size'], _buckets, gConfig['layer_size'], gConfig['num_layers'], gConfig['max_gradient_norm'], gConfig['batch_size'], gConfig['learning_rate'], gConfig['learning_rate_decay_factor'], forward_only=forward_only)
  File "C:\Users\user\Desktop\new\python source\PycharmProjects\untitled2\tensor\tensorflow_chatbot-master\tensorflow_chatbot-master\seq2seq_model.py", line 142, in __init__
    self.outputs, self.losses = tf.nn.seq2seq.model_with_buckets(
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'seq2seq'

**Comment by maxim5** [comment]
As for the warning, see [this question on StackOverflow](https://stackoverflow.com/q/47068709/712995). And also #78

**Comment by KhajaMoinuddin** [comment]
if you write a simple tensorflow program as well you will get this warning. but the program should work.
the issue looks to be here 
module 'tensorflow.python.ops.nn' has no attribute 'seq2seq'
i think you are at some latest version of tensorflow. go back to some older version and it will work
