### ISSUE TITLE
Cannot test after training!

### ISSUE THREAD

**Issue by steve3nto** [llSourcell/tensorflow_chatbot#80]
I trained the net for 38100 steps reaching perplexity lower than 5 and wanted to test, but when I change to test mode I get this error:

```
>> Mode : test

Reading model parameters from working_dir/seq2seq.ckpt-38100
Traceback (most recent call last):
  File "execute.py", line 355, in <module>
    decode()
  File "execute.py", line 228, in decode
    enc_vocab, _ = data_utils.initialize_vocabulary(enc_vocab_path)
  File "/home/stefano/Code/trueyou-app/chatbot/data_utils.py", line 97, in initialize_vocabulary
    assert len(vocab) == len(rev_vocab)
AssertionError
```

what is wrong with the vocab and rev_vocab? does anybody know how to fix this?

I am using python 2.7.14 and tensorflow 0.12.1, installed in an anaconda environment using pip.

**Comment by Rabisha** [comment]
I am also getting the same error.can anyone have the complete cleanup?
