### ISSUE TITLE
Py to Exe 

### ISSUE THREAD

**Issue by ObregonRafa** [llSourcell/tensorflow_chatbot#99]
Hi, 

I am trying to convert my python code to exe, but is returning the error below:

----------------------------------------
'utf-8' codec can't decode byte 0xc6 in position 153: invalid continuation byte
These are the bytes around the offending byte:
----------------------------------------
An error occurred, traceback follows:
Traceback (most recent call last):
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\auto_py_to_exe\__main__.py", line 227, in convert
    pyi.run() # Execute PyInstaller
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\hooks\hook-zmq.py", line 18, in <module>
    hiddenimports = ['zmq.utils.garbage'] + collect_submodules('zmq.backend')
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 626, in collect_submodules
    repr(pkg_dir), package))
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 85, in exec_statement
    return __exec_python_cmd(cmd)
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 72, in __exec_python_cmd
    txt = exec_python(*cmd, env=pp_env)
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\compat.py", line 580, in exec_python
    return exec_command(*cmdargs, **kwargs)
  File "c:\users\sirtec\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\compat.py", line 370, in exec_command
    out = out.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 153: invalid continuation byte

thank you if you can help me

**Comment by rawnullbyte** [comment]
same problem
